# This playbook is to be used to push spines and leafs config

---
- hosts: spine
  gather_facts: no
  tasks:
  - name: Push spine interfaces configurations
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_interface.cfg"
    
  - name: Push spine mlag + routing configurations
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_spine.cfg"


- hosts: leaf
  gather_facts: no
  tasks:
  - name: Push leaf interfaces configurations
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_interface.cfg"
    
  - name: Push leafs mlag configurations
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_leaf.cfg"



- hosts: server
  gather_facts: no
  tasks:
  - name: Push server interfaces configurations
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_interface.cfg"
    
  - name: Push servers route configurations
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_host.cfg"