---
- hosts: spine
  gather_facts: no
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env', 'PWD')}}/vars/underlay/yml"
      name: underlay
  - name: Create template
    template:
      src: "{{lookup('env', 'PWD')}}/templates/spine.j2"
      dest: "{{(lookup,'env','PWD')}}/configs/{{inventory_hostname}}_spine.cfg"